# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lcsimul_dev_comp_time <- function() {
    .Call('_lcsimul_dev_lcsimul_dev_comp_time', PACKAGE = 'lcsimul.dev')
}

lc_simulate_cpp <- function(tps, tp_limits, start_age, end_age, periods_per_year, N_states, initial_healthy_population, interventions_p, options_p, costs_p) {
    .Call('_lcsimul_dev_lc_simulate_cpp', PACKAGE = 'lcsimul.dev', tps, tp_limits, start_age, end_age, periods_per_year, N_states, initial_healthy_population, interventions_p, options_p, costs_p)
}

